type Query {
  app: String
}

type Mutation {
  app: String
}

type Pagination {
  page: Int!
  nextPage: Int
}

input PaginationInput {
  page: Int!
}

# Documents

fragment Pagination on Pagination {
  page
  nextPage
}
