extend type Query {
  session: Session!
}

extend type Mutation {
  register(input: RegisterInput!): Session!
  login(input: LoginInput!): Session!
}

type Session {
  token: String!
  user: User!
}

input RegisterInput {
  email: String!
  role: UserRole!
}

input LoginInput {
  email: String!
}

# Documents

fragment Session on Session {
  token
  user {
    ...User
  }
}

query Session {
  session {
    ...Session
  }
}

mutation Register ($input: RegisterInput!) {
  register(input: $input) {
    ...Session
  }
}

mutation Login ($input: LoginInput!) {
  login(input: $input) {
    ...Session
  }
}
