type Query {
    auth: Auth!
}

type Mutation {
    register(input: RegisterInput!): Auth!
    login(input: LoginInput!): Auth!
}

type Auth {
    token: String!
    user: User!
}

input RegisterInput {
    email: String!
    role: UserRole!
}

input LoginInput {
    email: String!
}

# Documents

query Auth {
    auth {
        token
        user {
            ...User
        }
    }
}

mutation Register ($input: RegisterInput!) {
    register(input: $input) {
        token
        user {
            ...User
        }
    }
}

mutation Login ($input: LoginInput!) {
    login(input: $input) {
        token
        user {
            ...User
        }
    }
}
